# GNU GENERAL PUBLIC LICENSE
# Version 3, 29 June 2007
#
# Copyright (C) 2025 Carlos Camacho and authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
name: 'PullHero'
description: 'A Python-based Review assistant'
author: 'Carlos Camacho'
branding:
  icon: message-square
  color: blue
inputs:
  api-key:
    description: 'API key for DeepSeek/OpenAI'
    required: true
  provider:
    description: 'AI provider (deepseek/openai)'
    default: 'openai'
    required: false
  model:
    description: 'Model name'
    default: 'gpt-4-turbo'
    required: false
  digest-length:
    description: 'Max digest length'
    default: '4096'
    required: false
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install requirements
      run: |
        pip install -r requirements.txt
      shell: bash

    - name: Run review
      shell: bash
      env:
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        python pullhero.py
